### ISSUE TITLE
Plunger on web3.py 3.16.2 overrides only the first pending transaction

### ISSUE THREAD

**Issue by reverendus** [makerdao/plunger#1]
This happened to me a few times today:

```
There are 7 pending transactions on kovan from 0x0046f01ad36027.......................ba8:

                              TxHash                                 Nonce
==========================================================================
0x1360b5e35f507cd47573764bda246bbe8459bf960e1f57858f1fb012e64869a4    1113
0x54ece598ee11765075ba1343efd9100dab961e5b69d5e749582443a2d508edf5    1114
0x15c4bf5e56ffd40830c664db5ac80f60bd7c8b485deb4d325823278b150275e1    1115
0x20ed34f532548ebd6557ac93b0bee465b185be2f6075f72f6fa0de15305ab74d    1116
0xc4688de61d2369a1f95044acde41d63be54a3415733b6ecaf032690a73c055c2    1117
0x7a2f5e20c166c0c81ca555f5f316c33f28acb73303bc7eeb4be431dfdf19aea8    1118
0x88abea7fd2a7f1c6446036be41e11e2ba7173ae168187bcc49a883e87ae70b80    1119

Sent replacement transaction with nonce=1113, gas_price=13000000000, tx_hash=0x4d2a125043cd43a2a12583dcbcc8bdd09a99d7c3c6a5d5cfb07fca913f309598.
Failed to send replacement transaction with nonce=1114, gas_price=13000000000.
   Error: {'code': -32015, 'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 1000000000000")'}
Failed to send replacement transaction with nonce=1115, gas_price=13000000000.
   Error: {'code': -32015, 'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 1000000000000")'}
Failed to send replacement transaction with nonce=1116, gas_price=13000000000.
   Error: {'code': -32015, 'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 1000000000000")'}
Failed to send replacement transaction with nonce=1117, gas_price=13000000000.
   Error: {'code': -32015, 'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 1000000000000")'}
Failed to send replacement transaction with nonce=1118, gas_price=13000000000.
   Error: {'code': -32015, 'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 1000000000000")'}
Failed to send replacement transaction with nonce=1119, gas_price=13000000000.
   Error: {'code': -32015, 'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 1000000000000")'}
Waiting for the transactions to get mined...
^CTraceback (most recent call last):
  File "/Users/____/.pyenv/versions/3.6.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/____/.pyenv/versions/3.6.2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/____/Projects/MakerDAO/plunger/plunger/plunger.py", line 221, in <module>
    Plunger(sys.argv[1:]).main()
  File "/Users/____/Projects/MakerDAO/plunger/plunger/plunger.py", line 115, in main
    self.wait(transactions)
  File "/Users/____/Projects/MakerDAO/plunger/plunger/plunger.py", line 160, in wait
    time.sleep(1)
KeyboardInterrupt
```

**Comment by reverendus** [comment]
Parity version Parity/v1.7.6-stable-1953533-20171013/x86_64-macos/rustc1.20.0

**Comment by reverendus** [comment]
I have actually discovered that this bug is related to the recent `web3.py` upgrade to `3.16.2`. It doesn't happen on `3.11.1`. And it is not Parity-version related at all.

Temporary workaround it to run plunger a few times in some intervals, so it does have chance to ultimately override all transactions in the queue.

**Comment by reverendus** [comment]
Seems to be working fine again on 3.16.2. Weird. Closing.
